version: '3.8'
services:
  brnn:
    build:
      context: .
      dockerfile: BRNN_parallel3.1/Dockerfile
    volumes:
      - ./data:/app/data
      - ./train.dataset:/app/train.dataset
    command: tail -f /dev/null

  dnn:
    build:
      context: .
      dockerfile: DNN_n-to-n_1layer/Dockerfile
    volumes:
      - ./data:/app/data
      - ./train.dataset:/app/train.dataset
    command: tail -f /dev/null

volumes:
  data:


