OBJECTST = Layer.o MModel.o BRNN.o NNt.o NN.o Predict_thresholds.o
HEADERST = Layer.h MModel.h BRNN.h NNt.h NN.h Sequence.h 

CC	= g++
CFLAGS  = -O3 -fopenmp

Predict_thresholds :	$(OBJECTST) 
	$(CC) $(CFLAGS) -o $@ $(OBJECTST) $(LLIBS)

Predict_thresholds.o : Predict_thresholds.cxx $(HEADERST)
	$(CC) -c $(CFLAGS) $*.cxx

Layer.o : Layer.cxx $(HEADERST)
	$(CC) -c $(CFLAGS) $*.cxx

MModel.o : MModel.cxx $(HEADERST)
	$(CC) -c $(CFLAGS) $*.cxx

NNt.o : NNt.cxx $(HEADERST)
	$(CC) -c $(CFLAGS) $*.cxx

NN.o : NN.cxx $(HEADERST)
	$(CC) -c $(CFLAGS) $*.cxx
	
BRNN.o : BRNN.cxx $(HEADERST)
	$(CC) -c $(CFLAGS) $*.cxx


clean:
	rm *.o Predict_thresholds
